######################################################
# Port Setting
######################################################

# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 7892

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7893

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7894


######################################################
# Core Setting
######################################################
# Set to true to allow connections to the local-end server from
# other LAN IP addresses, such as docker application...
allow-lan: true

# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: Rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

hosts:
    mtalk.google.com: 108.177.125.188

######################################################
# External Control
######################################################
external-controller: :9090
external-ui: /usr/share/yacd


######################################################
# DNS Server
######################################################
dns:
  enable: true 
  ipv6: false
  listen: 0.0.0.0:53

  # lookup hosts and return IP record
  use-hosts: true                

  # use to resolve IP addresses of the DoH/DoT reslover that specific in 'nameserver'
  default-nameserver: 
    - 156.154.70.1
    - 1.0.0.1
    - 119.29.29.29

  # Lookup domain through a specific nameserver.
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  #Use Real IP, not use fake-ip
  fake-ip-filter: ['*.lan', 'stun.*.*.*', 'stun.*.*', time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, '*.ntp.org.cn', '*.openwrt.pool.ntp.org', time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, ntp.aliyun.com, ntp1.aliyun.com, ntp2.aliyun.com, ntp3.aliyun.com, ntp4.aliyun.com, ntp5.aliyun.com, ntp6.aliyun.com, ntp7.aliyun.com, time1.aliyun.com, time2.aliyun.com, time3.aliyun.com, time4.aliyun.com, time5.aliyun.com, time6.aliyun.com, time7.aliyun.com, '*.time.edu.cn', time1.apple.com, time2.apple.com, time3.apple.com, time4.apple.com, time5.apple.com, time6.apple.com, time7.apple.com, time1.google.com, time2.google.com, time3.google.com, time4.google.com, music.163.com, '*.music.163.com', '*.126.net', musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, '*.kuwo.cn', api-jooxtt.sanook.com, api.joox.com, joox.com, y.qq.com, '*.y.qq.com', streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, '*.xiami.com', '*.music.migu.cn', music.migu.cn, '*.msftconnecttest.com', '*.msftncsi.com', localhost.ptlogin2.qq.com, '*.*.*.srv.nintendo.net', '*.*.stun.playstation.net', 'xbox.*.*.microsoft.com', '*.ipv6.microsoft.com', '*.*.xboxlive.com']

  # Defines upstream DNS server, support resolve by udp, tcp, udp on specific port, tcp on specific port, DNS over TLS, DNS over HTTPS.
  # The traffic of DoH or DoT will not pass proxy. All the traffic will direct to the server.
  nameserver: ['https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query', 'https://1.12.12.12/dns-query', 'https://120.53.53.53/dns-query']

  # Defines upstream DNS fallback server
  # Concurrent request with nameserver
  # fallback: ['208.67.222.222:5353', '208.67.220.220:5353', '208.67.222.220:5353']
  fallback: ['208.67.222.222:5353', '208.67.220.220:5353', '208.67.222.220:5353', '208.67.220.222:5353', 'https://1.1.1.1/dns-query', 'https://1.1.1.2/dns-query', 'https://1.1.1.3/dns-query', 'https://1.0.0.1/dns-query', 'https://1.0.0.2/dns-query', 'https://1.0.0.3/dns-query', 'https://45.11.45.11/dns-query', 'https://146.112.41.2/dns-query', 'https://162.159.36.1/dns-query', 'https://162.159.46.1/dns-query', 'https://9.9.9.11:5053/dns-query', 'https://101.6.6.6:8443/dns-query', 'https://208.67.222.222/dns-query', 'https://208.67.220.220/dns-query', 'https://185.222.222.222/dns-query', 'https://101.101.101.101/dns-query', 'https://149.112.112.11:5053/dns-query']

  # clash will use fallback results in certain condition.
  fallback-filter: 
    # Except for this country, all other countries' ip are considered contaminated.
    geoip: true
    geoip-code: CN

    # IPs in these subnets will be considered polluted,
    ipcidr: 
      - 240.0.0.0/4

    # Domains in these list will be considered polluted
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'

######################################################
# Tun Device
######################################################
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true

  # hijack the DNS request which send by hardcode DNS application, to make them to get fake-ip.
  # dns-hijack:
  #   - tcp://8.8.8.8:53
  #   - 8.8.8.8:1053

######################################################
# Profile
######################################################
profile:
  # Tracing is a dashboard which provide a large number of charts, help you debugging what happened in clash and why it's happened.
  tracing: true

  # store the select results in $HOME/.cache.
  # When restart occurs, Clash will automatically apply these results.
  # store-selected: true

  # Persistent Fake IP records
  # store-fake-ip: true


######################################################
# Proxies
######################################################
